{% set name = "humanleague" %}
{% set version = "2.1.5" %}
{% set sha256 = "7f770d85e661f27170f680a6df1acf032b1c40baea6e3cc64313965a5ce25425" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py < 34]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
  run:
    - python
    - numpy >= 1.18

test:
  imports:
    - humanleague

about:
  home: https://github.com/virgesmith/humanleague
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsynthesis using quasirandom sampling and/or IPF
  dev_url: https://github.com/virgesmith/humanleague

extra:
  recipe-maintainers:
    - virgesmith
